# Generated by Django 4.1.5 on 2023-01-09 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager_app', '0003_alter_taskmodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtaskmodel',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='taskmodel',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
