# Generated by Django 4.1.5 on 2023-01-23 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdb_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplication',
            name='feedback',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rdb_app.feedback'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
