# Generated by Django 4.1.5 on 2023-01-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager_app', '0002_alter_taskmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'not started'), (1, 'Strated'), (2, 'Working'), (3, 'Done')]),
        ),
    ]
