# Generated by Django 4.1.5 on 2023-01-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager_app', '0004_rename_task_id_subtaskmodel_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not started'), (1, 'Strated'), (2, 'Working'), (3, 'Done')]),
        ),
    ]
