# Generated by Django 4.1.5 on 2023-01-13 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=100)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('salary_date', models.DateTimeField()),
                ('salary', models.DecimalField(decimal_places=3, max_digits=10)),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_image', models.ImageField(blank=True, upload_to='employee-img/')),
            ],
        ),
        migrations.CreateModel(
            name='OneToManyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('employee_assigned', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orm_practice_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ManyToManyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('employee_assigned', models.ManyToManyField(to='orm_practice_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ForeignProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('Employee_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm_practice_app.employee')),
            ],
        ),
    ]
