# Generated by Django 4.1.5 on 2023-01-13 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_practice_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
