# Generated by Django 4.1.5 on 2023-01-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_practice_app', '0002_rename_employee_id_employee_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manytomanyproject',
            name='employee_assigned',
            field=models.ManyToManyField(blank=True, to='orm_practice_app.employee'),
        ),
    ]
